server.port=8081
spring.application.name=notificaciones-service
spring.threads.virtual.enabled=true

weather.api.url=https://api.weatherapi.com/v1/current.json
weather.api.key=81f52afc995a4f5d91c42911260507
weather.api.location=Buenos Aires
weather.api.language=es

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=disenoprueba98@gmail.com
spring.mail.password=kdst wuxd hhky zhgr
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

